feat(motion_velocity_smoother): change max_lateral_accel from 0.8 to 1.0
autowarefoundation/autoware.universe pull request #2057
Opened 2022-10-13 01:33 UTC by maxime-clem

Signed-off-by: Maxime CLEMENT <maxime.clement@tier4.jp>

## Description

This PR increases the value of the `max_lateral_accel` parameter in the `motion_velocity_smoother` node. allowing to drive at higher velocities in curves.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-10-13 02:02 UTC, takayuki5168 approved these changes
LGTM

2022-10-13 02:04 UTC, taikitanaka3 commented
@maxime-clem 
can you add PR to tier4/autoware_launch too?

2022-10-13 02:23 UTC, maxime-clem commented
> @maxime-clem can you add PR to tier4/autoware_launch too?

Done: https://github.com/tier4/autoware_launch/pull/512

2022-10-13 02:33 UTC, takayuki5168 requested changes
By discussion with Max-san, we'd better apply the change only to the specific vehicle.

2022-10-17 01:49 UTC, maxime-clem commented
Following discussions with @TakaHoribe and @tkimura4 I am reopening this PR.

2022-10-25 04:26 UTC, takayuki5168 commented
@TakaHoribe @tkimura4 Could you approve if this PR is okay for you.

2022-10-25 05:55 UTC, tkimura4 approved these changes
LGTM

2022-10-25 06:34 UTC, takayuki5168 approved these changes

2022-10-25 06:36 UTC, merged