refactor(lidar_apollo_segmentation_tvm/_nodes): remove autoware_auto_common dependency
autowarefoundation/autoware.universe pull request #2234
Opened 2022-11-07 14:21 UTC by takayuki5168

Signed-off-by: Takayuki Murooka <takayuki5168@gmail.com>

## Description
related to https://github.com/autowarefoundation/autoware.universe/issues/2229
remove autoware_auto_common from lidar_apollo_segmentation_tvm/_nodes

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-11-07 14:23 UTC, takayuki5168 commented
@yukke42 @yukkysaito 
I'm not familiar with these packages, but I wanna remove autoware_auto_common which is autoware.auto's common package.
For this reason, I created this PR. Could you check this PR please.

2022-11-07 14:25 UTC, yukkysaito commented
@esteve Do you know the background and benefits of the introduction of these types?

2022-11-08 00:29 UTC, kenji-miyake commented
Regarding this kind of code, let's refer to https://www.autosar.org/fileadmin/user_upload/standards/adaptive/21-11/AUTOSAR_RS_CPP14Guidelines.pdf and follow the latest recommendation.

https://autowarefoundation.github.io/autoware-documentation/main/contributing/coding-guidelines/languages/cpp/

2022-11-08 02:48 UTC, takayuki5168 commented
@kenji-miyake Could you give me more hint of how to refer to the guideline.

FYI: There is no behavior change with this PR since bool8_t, float32_t, float64_t is defined as bool, float, double respectively here.
https://github.com/autowarefoundation/autoware.universe/blob/7829c07d9a982054638312a44d4f6c374f8aa04d/common/autoware_auto_common/include/common/types.hpp#L39-L47

2022-11-09 14:55 UTC, xmfcx approved these changes

2022-11-09 17:08 UTC, xmfcx commented
(Please ignore my review, it was a dummy test)

> @kenji-miyake Could you give me more hint of how to refer to the guideline. (-> Explained in a chat.)

@takayuki5168 I've opened up the following discussion to talk about it: https://github.com/orgs/autowarefoundation/discussions/3016

2022-11-16 12:55 UTC, ambroise-arm commented
I feel like this PR is a step backwards if long term we want to indeed have fixed-width types.
Also, I don't understand the rational of removing the common package just because it is an autoware.auto package. It could simply be renamed.
And as for the "annoying dependencies" it creates, isn't it the case for any common package that aims at being used in several other packages in order to de-duplicate code?

In any case, those are not strongly held opinions and I don't oppose going ahead with the change.

2022-11-16 13:40 UTC, xmfcx commented
@ambroise-arm 
> I don't understand the rational of removing the common package just because it is an autoware.auto package. It could simply be renamed.

It's not because it is an Autoware.Auto package, it's because it's a dependency. In https://github.com/orgs/autowarefoundation/discussions/3016 we've discussed if we should create a similar package for types in Autoware Core.

> I feel like this PR is a step backwards if long term we want to indeed have fixed-width types.

As discussed in https://github.com/orgs/autowarefoundation/discussions/3016 , here are some conclusions:
- Autoware doesn't require to be MISRA/AUTOSAR compliant in near future.
- We will encourage devs to use [`<cstdint>`](https://en.cppreference.com/w/cpp/header/cstdint) for integer types. And will try to add automatic checking features to CI to fix them automatically.
- When C++23 comes out and a ROS version supporting it comes out, we will use [`<stdfloat>`](https://en.cppreference.com/w/cpp/header/stdfloat)

As for `typedef bool8_t = bool` and `typedef char8_t = char` I think we can discuss it further.

> And as for the "annoying dependencies" it creates, isn't it the case for any common package that aims at being used in several other packages in order to de-duplicate code?

Since types are the most essential things, it needs to be included in every package. We will of course have these kind of things if they are necessary. But what we are discussing is about whether they are necessary or not for the current state of the Autoware, the users etc.

Please add your inputs to the [discussion](https://github.com/orgs/autowarefoundation/discussions/3016) as well.

2022-11-16 14:38 UTC, ambroise-arm commented
> It's not because it is an Autoware.Auto package, it's because it's a dependency.

I may have misunderstood the meaning of the initial comment https://github.com/autowarefoundation/autoware.universe/pull/2234#issuecomment-1305691570. Alright then.

> We will encourage devs to use `<cstdint>` for integer types.

I had missed that the PR only replaced `floatXX_t` and `bool8_t`. Although it should also replace `char8_t ` by `char`. It probably won't compile in the current state (not picked up in CI as it doesn't compile the package by default).

2022-11-30 01:29 UTC, yukkysaito commented
@takayuki5168 Can you resolve some conflicts?

2023-01-10 08:27 UTC, takayuki5168 commented
@yukkysaito @xmfcx I resolved the conflicts.

2023-01-10 08:29 UTC, takayuki5168 commented on perception/lidar_apollo_segmentation_tvm/include/lidar_apollo_segmentation_tvm/cluster2d.hpp
>  using autoware::common::types::char8_t;
https://github.com/autowarefoundation/autoware.universe/pull/2234/commits/d7f9531f071714505f053d2b4231873f4d6b1cef
DONE

2023-01-10 08:29 UTC, yukkysaito commented
LGTM

2023-01-10 09:01 UTC, ambroise-arm requested changes

2023-01-20 14:52 UTC, esteve commented
> @esteve Do you know the background and benefits of the introduction of these types?

Sorry for the slow response, my notifications were not working properly. The reason for these types is mostly MISRA, because the built-in types don't have a defined size across all platforms, so by defining these aliases we can see quickly what size they have.

2023-03-22 09:43 UTC, xmfcx commented
@takayuki5168 I've moved this branch to AWF organization to collaborate easier. And made some fixes. https://github.com/autowarefoundation/autoware.universe/pull/3136

In order to build it, you need to run `colcon build --symlink-install  --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DDOWNLOAD_ARTIFACTS=1  --packages-select lidar_apollo_segmentation_tvm lidar_apollo_segmentation_tvm_nodes tvm_utility`

Without the ` --cmake-args -DDOWNLOAD_ARTIFACTS=1` argument, it will skip building the package.

2023-03-22 09:43 UTC, closed without merging

2023-03-22 10:18 UTC, takayuki5168 commented
@xmfcx Sorry about not handling this PR. I really appreciate your help.