chore: separate traffic_light_utils from perception_utils
autowarefoundation/autoware.universe pull request #4207
Opened 2023-07-10 01:04 UTC by miursh

## Description

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-07-10 03:27 UTC, yukkysaito commented
@miursh May I ask for some background on this PR?
I feel uncomfortable that only traffic light is separated from perception utils.

2023-07-10 03:27 UTC, yukkysaito requested changes
@miursh May I ask for some background on this PR?
I feel uncomfortable that only traffic light is separated from perception utils.

2023-07-10 03:30 UTC, yukkysaito commented
@miursh cc @mitsudome-r 
Thanks for the updated PR description.
If you want to separate them, I'd like to go from perception_utils to object_recognition_utils.

2023-07-10 03:41 UTC, miursh commented
@yukkysaito 
Thank you for your comment.
Do you mean separating into 'traffic_light_utils' and 'object_recognition_utils' instead of 'perception_utils'?

2023-07-10 06:36 UTC, yukkysaito commented
>Thank you for your comment.
Do you mean separating into 'traffic_light_utils' and 'object_recognition_utils' instead of 'perception_utils'?

@miursh Yes.
If it is a common use of object_recognition and traffic_light, then perception_utils is fine.

2023-07-10 09:53 UTC, miursh commented
@yukkysaito I have renamed the most of perception_utils to object_recognition_utils.
https://github.com/autowarefoundation/autoware.universe/pull/4207/commits/d7a8c57a8a1e79f2b5b129bf0772082d3f948112

2023-07-10 09:56 UTC, yukkysaito approved these changes
LGTM

2023-07-10 15:35 UTC, wep21 commented on common/traffic_light_utils/include/traffic_light_utils/traffic_light_utils.hpp
>  namespace traffic_light
@miursh This namespace seems redundant if the first namespace is changed from `perception_utils` to `traffic_light_utils`

2023-07-10 16:16 UTC, wep21 commented on common/perception_utils/include/perception_utils/prime_synchronizer.hpp
> + * @brief  This class implemented a multi-topic approxiamate time synchronizer.
```suggestion
 * @brief  This class implemented a multi-topic approximate time synchronizer.
```

2023-07-11 04:17 UTC, yukke42 approved these changes
LGTM

2023-07-12 04:45 UTC, merged