Fix sim z
autowarefoundation/autoware.universe pull request #4256
Opened 2023-07-12 08:32 UTC by TakaHoribe

## Description

Since the initial pose topic contains an appropriate z position value by default, add an option to use the initial pose for z-position. This enables the z-position calculation when the target trajectory is not planned.

![image](https://github.com/autowarefoundation/autoware.universe/assets/21360593/909bda88-e878-4fbe-9851-4ffc5e29ef47)

## Tests performed

run psim

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-07-12 08:44 UTC, tkimura4 approved these changes

2023-07-12 09:03 UTC, isamu-takagi requested changes
I think Z position of initial pose should be only used in set_initial_state.

2024-01-21 09:26 UTC, TakaHoribe commented
@isamu-takagi This PR is modified following your comment. Would you check it?
https://github.com/autowarefoundation/autoware.universe/pull/4256#pullrequestreview-1525876794

2024-01-22 00:51 UTC, isamu-takagi approved these changes
LGTM

2024-01-22 11:22 UTC, merged