feat(ekf_localizer): add diagnostics
autowarefoundation/autoware.universe pull request #4914
Opened 2023-09-07 09:00 UTC by YamatoAndo

## Description

Add ekf_localizer's diagnostics.

![ekf_diagnostics](https://github.com/autowarefoundation/autoware.universe/assets/13819566/0a0d3ab1-4d0e-4aad-a8cb-6cb44484e0ea)

Please refer to the readme for the conditions that trigger WARN/ERROR states.

## Related links

## Tests performed

I have confirmed the following
- The logging simulator works with the sample rosbag
- The diagnostic state triggers WARN/ERROR under the conditions mentioned in the readme
- The unit test is passed

## Notes for reviewers

After merging this pr, I will modify [system_error_monitor.param.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/system/system_error_monitor/config/system_error_monitor.param.yaml) and [diagnostic_aggregator/localization.param.yaml](https://github.com/autowarefoundation/autoware.universe/blob/main/system/system_error_monitor/config/diagnostic_aggregator/localization.param.yaml) to notify ekf_localizer's state to the autoware system.

## Interface changes

-  add a new published topic 
   - `/diagnostics` 
- add parameters
  - `diagnostics_update_rate`
  - `pose_no_update_count_threshold_warn`
  - `pose_no_update_count_threshold_error`
  - `twist_no_update_count_threshold_warn`
  - `twist_no_update_count_threshold_error`

## Effects on system behavior

 N/A

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-09-07 10:52 UTC, Motsu-san requested changes
Big commit.
Could you separate the commit fc1dd2f97294fe0f137ad559396c3ddce22d3dc3 to feature changes, tests and docs(ex. README)?

2023-09-08 00:46 UTC, KYabuuchi commented
Thank you for creating the pull request.  I have confirmed that the diagnostics works well in my environment too.  :+1:
Please wait a bit for the implementation review.

2023-09-08 02:42 UTC, YamatoAndo commented
@SakodaShintaro 
This node is single-threaded, so parallel processing does not occur.
So I believe that checkProcessActivated will not be called in parallel while the destructor is running.

2023-09-08 02:44 UTC, YamatoAndo commented
If my understanding is incorrect, please let me know.

2023-09-08 03:55 UTC, SakodaShintaro commented
@YamatoAndo 
Oh, I see.  I understood that the diag is a one of single-threaded timer callback which runs on the same thread as ekf. Then it looks fine.

I would like to check the diagnostics working, but how did you get the image shown at the beginning of the Description?

2023-09-08 05:09 UTC, YamatoAndo commented
@SakodaShintaro  I used following commnad to get that image.
`$ ros2 run rqt_runtime_monitor rqt_runtime_monitor`

2023-09-08 05:26 UTC, YamatoAndo commented
Since there is a possibility of making significant changes, I will temporarily convert to draft.

2023-09-13 10:54 UTC, YamatoAndo commented
@KYabuuchi @SakodaShintaro I have reopened the PR. Please review again.

2023-09-13 23:55 UTC, SakodaShintaro approved these changes
Looks Good To Me

2023-09-14 05:05 UTC, KYabuuchi commented on localization/ekf_localizer/src/diagnostics.cpp
> +// When all stat_array entries are 'OK,' the message of merged_stat will be empty
When this comment is fixed I will approve the PR.

2023-09-14 05:12 UTC, KYabuuchi approved these changes
:+1:

2023-09-14 07:41 UTC, YamatoAndo commented
@Motsu-san Could you please approve this pr?

2023-09-20 00:44 UTC, kminoda approved these changes
LGTM

2023-09-20 01:22 UTC, Motsu-san approved these changes
I approve this pull-request even without organizing the commits due to the circumstances of the squash merge rule. I hope that the pull-request will become smaller in size, which is a prerequisite for squash merge in the future.

2023-09-20 01:45 UTC, kminoda commented
@Motsu-san Thank you!

2023-09-20 02:34 UTC, merged