refactor(perception/ground_segmentation) : rework parameters
autowarefoundation/autoware.universe pull request #5777
Opened 2023-12-05 06:28 UTC by karishma1911

## Description
Implement the ROS Node configuration layout described in https://github.com/orgs/autowarefoundation/discussions/3371 for the perception_ground_segmentation

1. Remove the default value from the source code in order to ensure all parameter values are passed from the parameter files.
2.create schema

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-12-07 00:23 UTC, badai-nguyen requested changes
@karishma1911 Thank you for you PR, 
IMO: since all default parameters of 3 filters will be removed, then those default parameters should be listed somewhere like `xx_ground_filter.param.yaml` in `config/`. Otherwise the current launch for specific scan_ground_filter (`scan_ground_filter.launch.py`) cannot be executed. 
We are sorry that default launch.py for remaining `ransac_ground_filter` and `ray_ground_filter` was not maintained well yet.

2023-12-07 05:34 UTC, karishma1911 commented on perception/ground_segmentation/src/ransac_ground_filter_nodelet.cpp
> +  plane_slope_threshold_ = declare_parameter(<double>"plane_slope_threshold");
Thank you for suggestion...
I push the changes you mentioned above.

2024-01-26 03:32 UTC, badai-nguyen commented
@karishma1911 
I have another comment.
Since some parameters use default values which only declared in `scan_ground_filter_nodelet.cpp` so `common_ground_filter` cannot started with your PR. One of the errors as below. Could you also add such missing parameters into [ground_segmentation.param.yaml](https://github.com/autowarefoundation/autoware_launch/blob/a13af90d620f63baa87b8920715c675f77371fda/autoware_launch/config/perception/obstacle_segmentation/ground_segmentation/ground_segmentation.param.yaml#L32) file also?
 
>Failed to load node 'common_ground_filter' of type 'ground_segmentation::ScanGroundFilterComponent' in container 'pointcloud_container': Component constructor threw an exception: Statically typed parameter 'radial_divider_angle_deg' must be initialized.

2024-05-17 01:26 UTC, kminoda commented
@karishma1911 Hi, thank you for your contribution! What is the status of this PR? If this is stale, can we make this PR draft for now? (Of course feel free to re-open if it's ready for review)

2024-05-24 10:06 UTC, idorobotics commented
@karishma1911 could you please provide updates?

2024-06-14 01:37 UTC, kminoda commented
@karishma1911 Please fix the PR or recreate as another one :pray:

2024-06-21 01:19 UTC, kminoda commented
@karishma1911 Let me convert this PR as a draft as it may be noisy for other developers. But feel free to reopen this PR once it is fixed. Thank you for your contribution!

2024-08-16 06:13 UTC, vividf commented
I'll close this PR for now, as it doesn't appear to be actively progressing.

2024-08-16 06:13 UTC, closed without merging