feat(crosswalk): ignore predicted path going across the crosswalk
autowarefoundation/autoware.universe pull request #5849
Opened 2023-12-12 08:59 UTC by soblin

## Description

## Related links

https://tier4.atlassian.net/browse/RT1-3967

## Tests performed

### before this PR

crosswalk stopline appears

#### case1

https://github.com/autowarefoundation/autoware.universe/assets/28677420/0c51b76b-8994-44c9-997b-083796e093ed

#### case2

https://github.com/autowarefoundation/autoware.universe/assets/28677420/50e7ed2c-45bb-4cc5-8064-170f9030a5ac

### after this PR

crosswalk stopline does not appear

#### case1

https://github.com/autowarefoundation/autoware.universe/assets/28677420/0d6d7021-511b-434c-8ccc-5b14ffd59c45

#### case2

https://github.com/autowarefoundation/autoware.universe/assets/28677420/62daa80d-e24f-4841-bf08-60788bf9019b

## Notes for reviewers

## Interface changes

## Effects on system behavior

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-12-12 10:13 UTC, yuki-takagi-66 requested changes

2023-12-12 10:13 UTC, yuki-takagi-66 commented on planning/behavior_velocity_crosswalk_module/src/scene_crosswalk.cpp
> +        const double direction_diff = tier4_autoware_utils::normalizeRadian(
It requires abs().

In addition, depends on the significance of this PR, mod() by \pi rad may be required.

2023-12-12 16:09 UTC, shmpwk commented
Case 2 video after this PR still seems to be uploading now ...?

2023-12-14 11:11 UTC, yuki-takagi-66 approved these changes

2023-12-14 13:31 UTC, shmpwk approved these changes
LGTM

2023-12-15 07:38 UTC, merged