fix(tracking_object_merger): fix bug and use param file
autowarefoundation/autoware.universe pull request #6168
Opened 2024-01-25 04:16 UTC by kminoda

## Description

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-01-26 00:45 UTC, yukkysaito approved these changes

2024-01-26 01:13 UTC, kminoda commented
@YoshiRi Would appreciate if you could briefly check this PR :pray: 
This will fix a bug, which will change the default parameter of `tracking_object_merger`. Let me know if it is better to set the default value something else.

2024-01-26 02:51 UTC, YoshiRi requested changes
Sorry, I forgot to change this logging settings. Could you fix it?

2024-01-26 02:51 UTC, YoshiRi commented on perception/tracking_object_merger/config/decorative_tracker_merger.param.yaml
> +    enable_logging: true
Thanks for reworking.
This packages logging information is too detailed, so I do not set this True now.

```suggestion
    enable_logging: false
```

2024-01-26 11:31 UTC, YoshiRi approved these changes
LGTM

2024-01-29 00:46 UTC, kminoda commented
@YoshiRi Would you also approve https://github.com/autowarefoundation/autoware_launch/pull/823?

2024-01-29 08:17 UTC, merged