Chore/radar crossing objects noise filter readme
autowarefoundation/autoware.universe pull request #6262
Opened 2024-02-01 00:34 UTC by scepter914

## Description

Fix README of `radar_crossing_objects_noise_filter`

## Tests performed

No need

## Effects on system behavior

No

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-02-01 13:05 UTC, HansRobo commented
I updated this branch to import https://github.com/autowarefoundation/autoware.universe/pull/6278.
This will help you pass build-and-test-differential faster.

2024-02-02 00:57 UTC, YoshiRi requested changes

2024-02-02 00:57 UTC, YoshiRi commented on perception/radar_crossing_objects_noise_filter/README.md
> +If this parameter is set smaller, more objects are considered noise. In detail. see algorithm chapter.
```suggestion
If this parameter is set smaller, more objects are considered noise. In detail, see algorithm chapter.
```

2024-02-02 00:57 UTC, YoshiRi commented on perception/radar_crossing_objects_noise_filter/README.md
> +If this parameter is set smaller, more objects are considered noise. In detail. see algorithm chapter.
```suggestion
If this parameter is set smaller, more objects are considered noise. In detail, see algorithm chapter.
```

2024-02-06 17:12 UTC, miursh approved these changes
LGTM

2024-02-08 10:35 UTC, YoshiRi approved these changes
LGTM

2024-02-08 11:07 UTC, merged