refactor(behavior_path_planner): remove unused drivable area parameters
autowarefoundation/autoware.universe pull request #6466
Opened 2024-02-21 04:19 UTC by maxime-clem

## Description

Remove unused parameters

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-02-21 04:20 UTC, kosuke55 approved these changes

2024-02-29 14:29 UTC, xmfcx commented
I've rebased it to the latest main, hopefully all the checks will run this time.

2024-02-29 14:45 UTC, xmfcx requested changes

2024-02-29 14:45 UTC, xmfcx commented on planning/behavior_path_avoidance_module/config/avoidance.param.yaml
> +
```suggestion

```

2024-02-29 14:45 UTC, xmfcx commented on planning/behavior_path_avoidance_module/config/avoidance.param.yaml
> +
removes the trailing spaces for the ci to pass

2024-03-01 01:40 UTC, maxime-clem commented
@xmfcx thank you for fixing the CI. Can you approve the PR ? It is blocked by your "request for change".

2024-03-01 02:47 UTC, xmfcx approved these changes
Sorry, sure!

2024-03-01 04:12 UTC, takayuki5168 approved these changes

2024-03-01 04:13 UTC, merged