fix(autoware_auto_tf2): modify build error in rolling
autowarefoundation/autoware.universe pull request #718
Opened 2022-04-17 18:03 UTC by wep21

## Description

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-04-18 10:57 UTC, esteve requested changes
Please apply the same solution as in https://github.com/autowarefoundation/autoware.universe/pull/720#discussion_r852040761

2022-04-18 10:58 UTC, esteve requested changes

2022-04-18 10:58 UTC, esteve commented on common/autoware_auto_tf2/CMakeLists.txt
> +    -Wno-error
Please apply the same solution as in https://github.com/autowarefoundation/autoware.universe/pull/720#discussion_r852040761

2022-04-21 13:48 UTC, esteve submitted a review, later dismissed
@kenji-miyake there's a bunch of spelling mistakes that were not introduced by this branch, but that have popped up anyway, could you fix them? Otherwise I can deal with them.

2022-04-21 13:51 UTC, kenji-miyake commented
@esteve Thank you for notifying me.
Okay, then I'll send another PR to fix them. Please review it later!

2022-04-21 13:58 UTC, kenji-miyake commented
@wep21 Thank you for fixing typos, but I think it's better to split PRs.
So could you wait for #751?

2022-04-21 13:59 UTC, esteve commented
@kenji-miyake sorry, I meant @wep21 :sweat_smile: , I guess I pinged you because I was reviewing #210

2022-04-21 14:01 UTC, kenji-miyake commented
Oh, lol. :smile:
But yeah, it's alright.

2022-04-21 14:02 UTC, wep21 commented
@kenji-miyake 

> So could you wait for https://github.com/autowarefoundation/autoware.universe/pull/751?

I will rebase after #751 is merged.

2022-04-21 16:46 UTC, wep21 commented
@esteve @kenji-miyake I've finished. Could you review again?

2022-04-24 14:19 UTC, kenji-miyake approved these changes

2022-04-24 14:21 UTC, kenji-miyake commented
@esteve It seems your comment https://github.com/autowarefoundation/autoware.universe/pull/718#discussion_r852042154 is resolved, I'll clear your review status. :bow:

2022-04-24 14:33 UTC, merged