add local cartesian option for origin value
autowarefoundation/autoware.universe pull request #725
Opened 2022-04-18 14:49 UTC by meliketanrikulu

Signed-off-by: melike <melike@leodrive.ai>

## Description
This PR is intended to add local small origin values to the gnss_poser package. Local cartesian is determined using Geographiclib. It takes a geodetic coordinate as origin and allows you to convert any other geodetic coordinate to local cartesian coordinates with the [Forward()](https://geographiclib.sourceforge.io/html/classGeographicLib_1_1LocalCartesian.html#acb5cdba37d411f0504c65489ff9f376c) method.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-04-19 07:49 UTC, YamatoAndo commented
@meliketanrikulu Thank you for your contribution!
You had issued a similar PR for map_loader before (https://github.com/autowarefoundation/autoware.universe/pull/627),  but I think it is complicated with two similar config files.
So I think it would be better to prepare them together as a global config file. 
Do you have any idea about such a thing?

2022-04-19 08:52 UTC, meliketanrikulu commented
> @meliketanrikulu Thank you for your contribution! You had issued a similar PR for map_loader before (#627), but I think it is complicated with two similar config files. So I think it would be better to prepare them together as a global config file. Do you have any idea about such a thing?

@YamatoAndo Thanks for your suggestion. You are right, it seems more appropriate to create a global config file. In which package would you recommend we create a global config file?

2022-04-19 10:43 UTC, mitsudome-r commented
@meliketanrikulu I think we can utilize something like global_param.launch.py that is proposed in https://github.com/autowarefoundation/autoware.universe/issues/143.

2022-04-19 16:19 UTC, xmfcx commented
@mitsudome-r let's create an issue for discussing how the map origin is updated/passed

2022-04-25 08:29 UTC, meliketanrikulu commented
@YamatoAndo @mitsudome-r @xmfcx Hello. I'm getting an error like this (https://github.com/autowarefoundation/autoware.universe/runs/6125866560?check_suite_focus=true) in the pipeline but when I compile the package in local computer, I can't see any problem. Also, I don't think the changes I made in the code will cause this error. Any idea what could be the reason? Thanks for your response.

2022-04-26 15:27 UTC, kenji-miyake commented
@YamatoAndo @meliketanrikulu I'll track it in this issue. So for now, please ignore the error. :pray: 
https://github.com/autowarefoundation/autoware.universe/issues/456

2022-04-27 07:53 UTC, meliketanrikulu commented
Thanks for your reply. In this case it is ready for review. Can you check this PR.

2022-05-10 09:04 UTC, meliketanrikulu commented
Hi @xmfcx @mitsudome-r @YamatoAndo . Can you take a look at this PR? ready for review.

2022-05-10 09:17 UTC, YamatoAndo commented
@mitsudome-r In this PR,  we don't need to consider global_param.launch.py?

> I think we can utilize something like global_param.launch.py that is proposed in https://github.com/autowarefoundation/autoware.universe/issues/143.

2022-05-10 09:52 UTC, meliketanrikulu commented
> @mitsudome-r In this PR, we don't need to consider global_param.launch.py?
> 
> > I think we can utilize something like global_param.launch.py that is proposed in #143.

Hello thanks for your reply @YamatoAndo .Maybe we can open another issue for this package and map_loader package. we can work on the global_param.yaml file in this issue.

2022-06-09 10:07 UTC, xmfcx commented on sensing/gnss_poser/include/gnss_poser/gnss_poser_core.hpp
> +  sensor_msgs::msg::NavSatFix nav_sat_fix_origin;
```suggestion
  sensor_msgs::msg::NavSatFix nav_sat_fix_origin_;
```

Since this is a private member variable, consider refactoring it this way.

2022-06-09 10:09 UTC, xmfcx requested changes
Apart from a simple refactor, rest seems well put to me, good job!

2022-06-10 16:50 UTC, xmfcx approved these changes

2022-06-13 11:14 UTC, merged