fix(emergency_handler,mrm_handler): check for ego speed when determining the gear command
autowarefoundation/autoware.universe pull request #7264
Opened 2024-06-04 07:33 UTC by danielsanchezaran

## Description

Currently, both handlers always output a DRIVE gear when an emergency message makes the ego stop, which causes a very dangerous behavior (at least in simulations) when the ego vehicle is going backwards and an emergency is triggered -> since the gear is changed to Drive and the ego is going backwards, the simulator gives a positive velocity to the ego and makes it shoot forward (See video). Note that I used a script to simulate the AEB module activating to make these tests easier.

[Screencast from 2024年05月28日 15時24分35秒.webm](https://github.com/autowarefoundation/autoware.universe/assets/25967964/02e668a6-622c-4e02-8b41-eb0b9b79ba22)

After this PR fix: 

https://github.com/autowarefoundation/autoware.universe/assets/25967964/edb4f21d-b009-4517-a8bf-9a04f342974c

## Related links

## Tests performed

PSIM

## Notes for reviewers

## Interface changes

### ROS Topic Changes

### ROS Parameter Changes

## Effects on system behavior

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-06-05 01:13 UTC, veqcc commented
@danielsanchezaran 
Looks nice!!

Does anyone know why the CI is failing?
![Screenshot from 2024-06-05 10-12-00](https://github.com/autowarefoundation/autoware.universe/assets/26951562/0e883e1c-13fa-4eae-b27d-9259acd4c202)

2024-06-05 07:03 UTC, veqcc requested changes

2024-06-06 01:27 UTC, veqcc approved these changes

2024-06-06 08:19 UTC, merged

2024-06-06 08:44 UTC, Autumn60 commented
@danielsanchezaran 
@veqcc 

Hi, I think the Line 585 contains a bug.
Can I fix it in [my PR](https://github.com/autowarefoundation/autoware.universe/pull/7297)?

https://github.com/autowarefoundation/autoware.universe/blob/5913c5c1b1e43157d8fd23bc2eaced4dfa7c6edd/system/mrm_handler/src/mrm_handler/mrm_handler_core.cpp#L582-L586