feat(freespace_planning_algorithms): implement option for backward search from goal to start
autowarefoundation/autoware.universe pull request #8091
Opened 2024-07-18 05:47 UTC by mkquda

## Description
When using A-star freespace planner, in most cases the path found will arrive at the goal with small offset in position and orientation due to the discretized search space. As a result the vehicle might not arrive with the exact desired pose.

For certain applications such as parking, matching the actual goal pose is important, therefore it useful to be able to configure the planner to do the search process backwards (starting from goal pose towards start pose).

## Changes
- Includes changes from preceding [PR](https://github.com/autowarefoundation/autoware.universe/pull/8089)
- Modified A-star expansion logic to support backward search
- Added parameter to configure search method (forward search or backward search)

## Related links

**Preceding PR's**
- https://github.com/autowarefoundation/autoware.universe/pull/8068
- https://github.com/autowarefoundation/autoware.universe/pull/8089

## How was this PR tested?
tested on psim.

## Notes for reviewers

This PR includes changes from a preceding [PR](https://github.com/autowarefoundation/autoware.universe/pull/8089). so please review the PR's in order.

## Interface changes

### ROS Parameter Changes

#### Additions and removals

| Change type   | Parameter Name | Type     | Default Value | Description       |
|:--------------|:---------------|:---------|:--------------|:------------------|
| Added | `search_method`   | `string` | `forward` | method of searching, start to goal or vice versa |

## Effects on system behavior

Can configure A-star search direction, forward search (start pose to goal pose) OR backward search (goal pose to start pose)

2024-08-02 16:42 UTC, armaganarsln requested changes
Can you please test with this issue: 
- https://github.com/autowarefoundation/autoware.universe/issues/8342

2024-08-15 09:20 UTC, armaganarsln approved these changes

2024-08-15 17:00 UTC, xmfcx commented on planning/autoware_freespace_planning_algorithms/src/astar_search.cpp
>    }
```suggestion
  waypoints_.waypoints.reserve(waypoints.size());
  
  for (size_t i = 0; i < waypoints.size() - 1; ++i) {
    const auto& current = waypoints[i];
    const auto& next = waypoints[i + 1];

    waypoints_.waypoints.push_back(current);

    if (current.is_back != next.is_back) {
      waypoints_.waypoints.push_back({
        is_backward_search_ ? next.pose : current.pose,
        is_backward_search_ ? current.is_back : next.is_back
      });
    }
  }
```

Maybe something like this to keep it more readable.

2024-08-15 17:03 UTC, xmfcx commented on planning/autoware_freespace_planning_algorithms/src/astar_search.cpp
Maybe add some check to make sure `waypoints` is not empty here. Or even to make sure it has at least 2 elements, not sure. Some operations below here depend on this.

2024-08-15 17:07 UTC, xmfcx commented
Could you rebase to the latest main?

2024-08-20 06:09 UTC, maxime-clem approved these changes
Looks good and parking works fine in Psim.

2024-08-21 04:33 UTC, kosuke55 approved these changes
LGTM for behavior path planner

2024-08-22 00:54 UTC, merged