feat(psim)!: enabling to launch Localization modules on psim
autowarefoundation/autoware.universe pull request #8212
Opened 2024-07-26 07:11 UTC by yuki-takagi-66

## Description
This PR provides launch settings to launch Localization modules on psim.

launch PR: 

## Related links

**Parent Issue:**

- Link

## How was this PR tested?

## Notes for reviewers

None.

## Interface changes

## Effects on system behavior

2024-07-26 08:25 UTC, takayuki5168 approved these changes

2024-07-26 10:17 UTC, kosuke55 commented on launch/tier4_simulator_launch/launch/simulator.launch.xml
> +            <arg name="ekf_enabled" value="true"/>
>  localization modules without NDT will be launched.

not NDT but ekf?

2024-07-26 10:21 UTC, kosuke55 approved these changes

2024-07-26 10:21 UTC, kosuke55 commented on launch/tier4_simulator_launch/launch/simulator.launch.xml
> +            <arg name="ekf_enabled" value="true"/>
this is just pose_initializer's args. sorry I misunderstood

2024-07-26 14:10 UTC, TakaHoribe commented on launch/tier4_simulator_launch/launch/simulator.launch.xml
> +    </group>
Why is this code necessary?

2024-07-29 03:41 UTC, yukkysaito requested changes
Same comment
https://github.com/autowarefoundation/autoware_launch/pull/1094#pullrequestreview-2203877252

2024-08-15 04:53 UTC, yuki-takagi-66 commented
@yukkysaito 
Thank you.
As we discussed internally, we need to achieve the following two goals: 
"maintain a simulator environment whose only dependent module is planning/control" and "evaluate planning/control modules, considering the characteristics of localization in a closed loop."
To achieve these two goals, the preceding PR https://github.com/autowarefoundation/autoware_launch/pull/1106 provided a mode-switching feature supporting three or more states.

2024-08-19 01:12 UTC, TakaHoribe approved these changes

2024-08-19 01:59 UTC, yukkysaito approved these changes

2024-08-19 08:51 UTC, merged