feat(universe_utils): add Polygon Clipping implementation to do boolean operation on Polygons (XOR, OR, AND)
autowarefoundation/autoware.universe pull request #8728
Opened 2024-09-03 06:12 UTC by mraditya01

## Description
Added new polygon clipping function within universe_utils to do boolean operation on multiple polygons using Greiner-Hormann clipping algorithm.

## Related links

**Parent Issue:**

- Link

## How was this PR tested?
Unit and random test.

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

2024-10-16 09:22 UTC, maxime-clem requested changes

2024-12-20 07:56 UTC, maxime-clem approved these changes

2024-12-24 08:14 UTC, maxime-clem commented on common/autoware_universe_utils/src/geometry/polygon_clip.cpp
> +  int32_t winding_num = 0;
this variable is never used.

2024-12-25 03:01 UTC, soblin approved these changes

2025-01-07 08:40 UTC, takayuki5168 approved these changes

2025-01-29 10:47 UTC, merged