devops dojo changes for autoware_planning_evaluator
autowarefoundation/autoware.universe pull request #8746
Opened 2024-09-03 16:05 UTC by odra

## Description

Implement ROS Node configuration according to the devops dojo instruction document for the "autoware_planning_evaluator" package.

## Related links

* https://github.com/orgs/autowarefoundation/discussions/3371

**Parent Issue:**

-  https://github.com/orgs/autowarefoundation/discussions/3371

## How was this PR tested?

```
colcon build --symlink-install --packages-up-to autoware_planning_evaluator
```

```
ros2 launch evaluator/autoware_planning_evaluator/launch/planning_evaluator.launch.xml
```

## Notes for reviewers

None.

## Interface changes

No interface changes per say, just moving the existing param files to the "config" folder and creating a json schema file containing that same information.

## Effects on system behavior

None.

2024-09-04 00:11 UTC, maxime-clem requested changes
The tests are failing because the path to the parameter file is not updated (https://github.com/autowarefoundation/autoware.universe/actions/runs/10692393280/job/29640731369?pr=8746).
Please also fix some typos such that the spell check passes (https://github.com/autowarefoundation/autoware.universe/actions/runs/10688815334/job/29640724521?pr=8746).

Finally the README fails to render: https://autowarefoundation.github.io/autoware.universe/pr-8746/evaluator/autoware_planning_evaluator/
```
FileNotFoundError: [Errno 2] No such file or directory: 'validator/autoware_planning_evaluator/schema/autoware_planning_evaluator.schema.json'
```

Otherwise the PR looks good and I will approve it once the above issues are fixed.

2024-09-05 11:44 UTC, odra commented
@maxime-clem could you review it again? I believe I've  applied the required changes.

2024-09-05 23:44 UTC, maxime-clem reviewed
Thank you for the changes. I think there is only one issue left to fix and then we can merge the PR.

2024-09-05 23:44 UTC, maxime-clem commented on evaluator/autoware_planning_evaluator/schema/autoware_planning_evaluator.schema.json
> +          "description": "trajectory object",
I think the [documentation rendering issue](https://autowarefoundation.github.io/autoware.universe/pr-8746/evaluator/autoware_planning_evaluator/) is caused by missing `type` fields.
```suggestion
          "description": "trajectory object",
          "type": "object",
```

2024-09-05 23:44 UTC, maxime-clem commented on evaluator/autoware_planning_evaluator/schema/autoware_planning_evaluator.schema.json
> +              "description": "lookahead object",
```suggestion
              "description": "lookahead object",
              "type": "object",
```

2024-09-12 18:56 UTC, odra commented on evaluator/autoware_planning_evaluator/schema/autoware_planning_evaluator.schema.json
> +              "description": "lookahead object",
Added in both now.

2024-09-12 20:45 UTC, maxime-clem approved these changes

2024-09-13 12:48 UTC, merged