fix(pose_initializer): Add topic subscription to direct initialization
autowarefoundation/autoware.universe pull request #8941
Opened 2024-09-23 13:56 UTC by meliketanrikulu

## Description
You need to call service to initialize directly now. [Documentation](https://github.com/autowarefoundation/autoware.universe/tree/main/localization/autoware_pose_initializer#direct-initial-position-set)
However, if you trust the GNSS pose, you may want to initialize directly with the GNSS pose. For example, we think that the pose coming from GNSS for the simulation environment can be used for initialization directly. We think that the feature of using GNSS poses should be added to activate the direct initialization feature for such cases.

This PR allows you to directly initialize the position from GNSS poses with a parameter change.
## Related links

**Parent Issue:**
https://github.com/autowarefoundation/autoware.universe/issues/8940
- Link

## How was this PR tested?

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

2024-09-23 15:25 UTC, meliketanrikulu commented
/review

2024-09-23 15:43 UTC, meliketanrikulu commented
/improve_extended

2024-09-24 06:36 UTC, YamatoAndo requested changes
This makes the ndt_enable and yabloc_enabled parameters meaningless. Please revise the implementation.

2024-09-24 13:19 UTC, meliketanrikulu commented
This PR parameter change is based on the addition of DIRECT initialization. However, instead of this, it seems more logical to decide whether the pose will be DIRECT initialized by checking if the covariance of the gnss poses is 0.For this reason I want to close this and open a new PR.
 However, the covariance values ​​of the GNSS poses that come in the autoware_pose_initializer package are automatically changed . This parameter decide the covariance values of GNSS poses --> https://github.com/autowarefoundation/autoware.universe/blob/d25e9a1bbedc176d4e29c70b3ed9586808bdf813/localization/autoware_pose_initializer/config/pose_initializer.param.yaml#L16

 What is the reason for this? Why are default values ​​assigned instead of using the covariance values ​​that come with the poses.
 @isamu-takagi @YamatoAndo

2024-09-25 09:20 UTC, YamatoAndo commented
> What is the reason for this? Why are default values ​​assigned instead of using the covariance values ​​that come with the poses.

It's not that we want the covariance of the GNSS, but rather, we want to determine the kind of distribution to use when spreading the particles.

2024-09-25 09:21 UTC, YamatoAndo commented
> it seems more logical to decide whether the pose will be DIRECT initialized by checking if the covariance of the gnss poses is 0

I don't think this method is a good approach.

2024-09-25 09:25 UTC, xmfcx commented
> > it seems more logical to decide whether the pose will be DIRECT initialized by checking if the covariance of the gnss poses is 0

> I don't think this method is a good approach.

@YamatoAndo -san, Why do you think so?

If all the covariances are 0, or lower than some threshold we define, it means, the pose is very reliable and we can use it for direct initialization.

Overriding the original covariances should be an optional feature, not the default.

The GNSS already provides this information.

2024-09-25 09:28 UTC, xmfcx commented
> It's not that we want the covariance of the GNSS, but rather, we want to determine the kind of distribution to use when spreading the particles.

Why shouldn't you distribute it along the covariance ellipse?

2024-09-25 10:27 UTC, YamatoAndo commented
> Why shouldn't you distribute it along the covariance ellipse?

In the first place, the position output by the GNSS receiver often does not match the correct position on the point cloud map. While GNSS positioning errors are one factor, it is difficult to perfectly align the point cloud map with GNSS positioning. Despite this, relying on the dispersion output by the GNSS receiver to determine the particle distribution is not a good idea.
Therefore, considering various errors, I believe it would be more robust to distribute particles with a wider spread than the dispersion output by the GNSS receiver.

2024-09-27 15:36 UTC, xmfcx commented
Let's discuss here:
[Proposal for Simplifying Pose Initialization in Autoware #5285](https://github.com/orgs/autowarefoundation/discussions/5285)

2024-09-27 15:36 UTC, closed without merging