feat(map_loader): add support for local cartesian projection
autowarefoundation/autoware.universe pull request #9238
Opened 2024-11-05 14:02 UTC by sebekx

lanelet map loader

## Description

Add LocalCaretsian (WGS84) projection support to map_loader.

**Requires:**
- https://github.com/tier4/tier4_autoware_msgs/pull/152
- https://github.com/autowarefoundation/autoware_msgs/pull/118

## Related links

- https://github.com/autowarefoundation/autoware.core/pull/181
- https://github.com/autowarefoundation/autoware_msgs/pull/118

## How was this PR tested?

Used map_loaded to load  lanelet with localCartesian(WGS84) projection.  

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

2024-11-06 05:44 UTC, TaikiYamada4 commented
@sebekx 
Could you please share your thoughts why you recommend this change?
Adding a new mapping projection doesn't only influence the `map_loader` but also make effects to other modules such as [`gnss_poser`](https://github.com/autowarefoundation/autoware.universe/tree/main/sensing/autoware_gnss_poser), [`MapProjectorInfo.msg`](https://github.com/tier4/tier4_autoware_msgs/blob/tier4/universe/tier4_map_msgs/msg/MapProjectorInfo.msg), and maybe more.

Since we cannot discuss or estimate the impact to the entire Autoware enough here, I would recommend you to create a discussion about adding LocalCartesian support to Autoware.

2024-11-14 09:53 UTC, TaikiYamada4 commented
@sebekx 

> We are using LocalCartesian in our stack with different implementation of localization components. Adding it in here shouldn't affect the system unless someone use it.

If so, then please add the information in README.md that LocalCartesian can only be used in `lanelet2_map_loader` and packages like `gnss_poser` doesn't support it.

Then I suppose the changes here is OK, but it's only in my sense.
I'm not sure what the reviewers of the [MapProjectorInfo.msg PR](https://github.com/tier4/tier4_autoware_msgs/pull/152) might say.

2024-11-22 09:21 UTC, sebekx commented
> If so, then please add the information in README.md that LocalCartesian can only be used in `lanelet2_map_loader` and packages like `gnss_poser` doesn't support it.

Ok, thanks, I have updated readme.

2024-12-23 06:18 UTC, TaikiYamada4 commented
@sebekx 
[
Since map_loader will move to Autoware.Core](https://github.com/orgs/autowarefoundation/discussions/5365), you shall resolve the conflicts here and the conversations happening in the PR of tier4_map_msgs soon if this is urgent.
Unless, there might be some other tasks coming up after map_loader is moved to Autoware.Core

2025-02-04 16:32 UTC, xmfcx commented
- @sebekx can you rebase this PR after updating https://github.com/tier4/tier4_autoware_msgs/pull/152 ?

2025-02-05 10:49 UTC, sebekx commented
> * @sebekx can you rebase this PR after updating [feat(tier4_map_msgs): add LocalCartesian const tier4/tier4_autoware_msgs#152](https://github.com/tier4/tier4_autoware_msgs/pull/152) ?

rebased and created pr:

* [autoware.core  PR](https://github.com/autowarefoundation/autoware.core/pull/181)
* [autoware_msgs PR](https://github.com/autowarefoundation/autoware_msgs/pull/118)

2025-02-19 05:06 UTC, TaikiYamada4 requested changes
I'm sorry for being late.
Could you fix this part?

2025-02-19 05:06 UTC, TaikiYamada4 commented on map/autoware_map_projection_loader/src/map_projection_loader.cpp
> +    msg.projector_type == tier4_map_msgs::msg::MapProjectorInfo::TRANSVERSE_MERCATOR) {
`tier4_map_msgs` went to `autoware_map_msgs` so could you fix this part?

2025-02-20 08:20 UTC, sebekx commented on map/autoware_map_projection_loader/src/map_projection_loader.cpp
> +    msg.projector_type == tier4_map_msgs::msg::MapProjectorInfo::TRANSVERSE_MERCATOR) {
yes, fixed

2025-02-25 04:35 UTC, xmfcx commented
@TaikiYamada4 could you review again?

2025-02-26 01:28 UTC, TaikiYamada4 approved these changes
LGTM

2025-02-26 01:29 UTC, merged