chore: change ml models location
autowarefoundation/autoware.universe pull request #938
Opened 2022-05-20 02:25 UTC by eratostennis

## Description

Change ml models location from google drive to AWS s3 in order to solve the following problem.
https://github.com/autowarefoundation/autoware/issues/200

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-05-20 02:38 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/package.xml
> +  <buildtool_depend>curl</buildtool_depend>
```suggestion
  <buildtool_depend>libcurl_vendor</buildtool_depend>
```

2022-05-20 02:38 UTC, wep21 commented on perception/lidar_centerpoint/package.xml
> +  <buildtool_depend>curl</buildtool_depend>
```suggestion
  <buildtool_depend>libcurl_vendor</buildtool_depend>
```

2022-05-20 02:39 UTC, wep21 commented on perception/tensorrt_yolo/package.xml
> +  <buildtool_depend>curl</buildtool_depend>
```suggestion
  <buildtool_depend>libcurl_vendor</buildtool_depend>
```

2022-05-20 02:40 UTC, wep21 commented on perception/traffic_light_classifier/package.xml
> +  <buildtool_depend>curl</buildtool_depend>
```suggestion
  <buildtool_depend>libcurl_vendor</buildtool_depend>
```

2022-05-20 02:40 UTC, wep21 commented on perception/traffic_light_ssd_fine_detector/package.xml
> +  <buildtool_depend>curl</buildtool_depend>
```suggestion
  <buildtool_depend>libcurl_vendor</buildtool_depend>
```

2022-05-20 02:44 UTC, wep21 commented
It may be more simple to use file(DOWNLOAD).

2022-05-25 11:20 UTC, eratostennis commented
> It may be more simple to use file(DOWNLOAD).

@wep21
I fixed it. Please review again.
Thanks.

2022-05-25 21:33 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/CMakeLists.txt
> +        file(DOWNLOAD https://awf.ml.dev.web.auto/perception/models/${FILE_NAME} ${FILE_PATH} STATUS DOWNLOAD_STATUS)
I guess you can use this argument to check md5 hash.
```
Additional options to DOWNLOAD are:

EXPECTED_HASH ALGO=<value>

Verify that the downloaded content hash matches the expected value, where ALGO is one of the algorithms supported by file(<HASH>). If it does not match, the operation fails with an error. It is an error to specify this if DOWNLOAD is not given a <file>.

EXPECTED_MD5 <value>
Historical short-hand for EXPECTED_HASH MD5=<value>. It is an error to specify this if DOWNLOAD is not given a <file>.
```

2022-05-25 21:54 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/CMakeLists.txt
> +    execute_process(COMMAND echo "start ${FILE_NAME}" 1>&2)
```suggestion
    message(STATUS "start ${FILE_NAME}")
```

2022-05-25 21:55 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/CMakeLists.txt
> +      execute_process(COMMAND echo "found ${FILE_NAME}")
```suggestion
      message(STATUS "found ${FILE_NAME}")
```

2022-05-25 21:55 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/CMakeLists.txt
> +        execute_process(COMMAND echo "same ${FILE_NAME}")
```suggestion
        message(STATUS "same ${FILE_NAME}")
```

2022-05-25 21:59 UTC, wep21 commented on perception/lidar_centerpoint/CMakeLists.txt
> +    execute_process(COMMAND echo "start ${FILE_NAME}" 1>&2)
Ditto

2022-05-25 21:59 UTC, wep21 commented on perception/tensorrt_yolo/CMakeLists.txt
> +  execute_process(COMMAND echo "start ${FILE_NAME}" 1>&2)
Ditto

2022-05-25 22:00 UTC, wep21 commented on perception/traffic_light_classifier/CMakeLists.txt
> +  execute_process(COMMAND echo "start ${FILE_NAME}" 1>&2)
Ditto

2022-05-25 22:00 UTC, wep21 commented on perception/traffic_light_ssd_fine_detector/CMakeLists.txt
> +  execute_process(COMMAND echo "start ${FILE_NAME}" 1>&2)
Ditto

2022-05-26 00:17 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/CMakeLists.txt
> +        message(STATUS "Downloaded file hash: ${DOWNLOADED_FILE_HASH}")
```suggestion
```
Unnecessary?

2022-05-26 00:17 UTC, wep21 commented on perception/lidar_apollo_instance_segmentation/CMakeLists.txt
> +      message(STATUS "Downloaded file hash: ${DOWNLOADED_FILE_HASH}")
Ditto

2022-05-26 22:10 UTC, wep21 approved these changes
LGTM

2022-05-27 00:37 UTC, wep21 requested changes
@eratostennis Could you make timeout time longer for huge models?

2022-05-27 01:46 UTC, eratostennis commented
> @eratostennis Could you make timeout time longer for huge models?

@wep21 I fixed it.

2022-05-27 02:15 UTC, wep21 approved these changes
LGTM

2022-05-27 06:32 UTC, merged