feat(autoware_cuda_pointcloud_preprocessor): a cuda-accelerated pointcloud preprocessor
autowarefoundation/autoware.universe pull request #9454
Opened 2024-11-25 08:31 UTC by knzo25

## Description

## Related links

**Parent Issue:**

- Link

## How was this PR tested?

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

2024-12-24 06:14 UTC, mojomex requested changes
Thank you for the amazing PR, these performance improvements are desperately needed.

I haven't checked the PR for functionality yet, but I'll leave my first round of comments here.

The main points I'd like to address are
* memory safety and idiomatic C++ (there is currently a lot of raw-pointer code which should be avoided whenever possible)
* modulatiry: currently the pipeline is hard-coded and all in one place. This makes the module hard to adapt to different projects, and hard to maintain individual modules in the pipeline.

Thank you for your time!

2025-01-07 09:05 UTC, manato commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  device_twist_3d_structs_ = host_twist_structs;
I suspect this code may cause GPU memory fragmentation and/or repeated implicit GPU memory allocation, both of which harm performance. To prevent such kind of issues, I would suggest using CUDA's memory pool functionality. I'll add suggestion code to the constructor of `CudaPointcloudPreprocessor`.

2025-01-07 09:09 UTC, manato commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +}
```suggestion
  cudaMemPoolProps pool_props;
  memset(&pool_props, 0, sizeof(cudaMemPoolProps));
  pool_props.allocType = cudaMemAllocationTypePinned;
  pool_props.handleTypes = cudaMemHandleTypePosixFileDescriptor;

  pool_props.location.type = cudaMemLocationTypeDevice;
  cudaGetDevice(&(pool_props.location.id));

  // cudaMemPool_t device_memory_pool_ needs to be declared as a member of this class
  cudaMemPoolCreate(&device_memory_pool_, &pool_props);
  MemoryPoolAllocator<TwistStruct2D> allocator_2d(device_memory_pool_);
  MemoryPoolAllocator<TwistStruct3D> allocator_3d(device_memory_pool_);
  device_twist_2d_structs_
      = thrust::device_vector<TwistStruct2D, MemoryPoolAllocator<TwistStruct2D>>(allocator_2d);
  device_twist_3d_structs_
      = thrust::device_vector<TwistStruct3D, MemoryPoolAllocator<TwistStruct3D>>(allocator_3d);
}

template <typename T>
class MemoryPoolAllocator {
 public:
  using value_type = T;
  MemoryPoolAllocator(cudaMemPool_t pool) : m_pool(pool) {}

  T* allocate(std::size_t n) {
    void* ptr = nullptr;
    cudaMallocFromPoolAsync(&ptr, n * sizeof(T), m_pool, cudaStreamDefault);
    return static_cast<T*>(ptr);
  }

  void deallocate(T* ptr, std::size_t) {
    cudaFreeAsync(ptr, cudaStreamDefault);
  }

 protected:
  cudaMemPool_t m_pool;
};  // MemoryPoolAllocator
```

This is a suggestion to apply CUDA's memory pool functionality to the `thrust::device_vector` exploiting custom allocator capability.
(I just confirmed this code can pass compilation but not performed test run. If you feel this suggestion is appropriate via another PR, please let me know)

2025-01-10 09:28 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/schema/cuda_pointcloud_preprocessor.schema.json
I agree that having prefixes would be better, but to ease transition, I am using the same parameters as the current pipeline. This is how it is done in the `aip_launcher`:

```python
        nodes.append(
            ComposableNode(
                package="autoware_cuda_pointcloud_preprocessor",
                plugin="autoware::cuda_pointcloud_preprocessor::CudaPointcloudPreprocessorNode",
                name="cuda_pointcloud_preprocessor_node",
                parameters=[
                    preprocessor_parameters,
                    load_composable_node_param("distortion_corrector_node_param_file"),
                    ring_outlier_filter_node_param,
                ],
                remappings=[
                    ("~/input/pointcloud", "cuda_points"),
                    ("~/input/pointcloud/cuda", "cuda_points/cuda"),
                    ("~/input/twist", "/sensing/vehicle_velocity_converter/twist_with_covariance"),
                    ("~/input/imu", "/sensing/imu/imu_data"),
                    ("~/output/pointcloud", "pointcloud_before_sync"),
                    ("~/output/pointcloud/cuda", "pointcloud_before_sync/cuda"),
                ],
                # The whole node can not set use_intra_process due to type negotiation internal topics
                # extra_arguments=[{"use_intra_process_comms": LaunchConfiguration("use_intra_process")}],
            )
        )
```

For this reason, at least in this first PR, I would like to leave it as is

2025-01-10 09:31 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  uint32_t * mask1, uint32_t * mask2, uint32_t * mask3, int num_points, uint32_t * output_mask)
@manato 
I wanted to leave optimizations like this for a second PR, but it is true that for the `__restrict__` keyword, there is no meaning in waiting. Thanks :pray:

2025-01-10 09:58 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  InputPointType * d_points, uint32_t * output_mask, int num_points, float min_x, float min_y,
As I mentioned in another comment, I planned to leave `__restrict__` and strided loops for the next PR, but for the `__reestrict__` there is no much meaning in waiting.

That being said, I had heard that the compiler will only consider the keyword if all the pointers have it. Is that true?

2025-01-10 10:11 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  if (idx < num_points) {
Would warps not diverge anyways? 
I had understood that under warp divergence, the cost would simply be the cost of all paths
https://people.maths.ox.ac.uk/gilesm/cuda/lecs/lec3-2x2.pdf

Eons ago I remember that for old CPU compilers the most common path should go first. I know that GPUs do not have branch prediction, which renders this concern null, but this became a habit.

2025-01-10 10:12 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  if (idx < num_points) {
Replied in an earlier comment (just to signal that it is being discussed elsewhere)

2025-01-10 10:49 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +      point.time_stamp > twist.last_stamp_nsec ? point.time_stamp - twist.last_stamp_nsec : 0;
Old evidence:
https://gist.github.com/allanmac/5125376

2025-01-10 10:55 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +    azimuth_diff = azimuth_diff < 0.f ? azimuth_diff + 2 * M_PI : azimuth_diff;
Are you sure these tricks are still necessary?

https://forums.developer.nvidia.com/t/overhead-of-warp-divergence-vs-extra-multiplication-by-0-or-1/28413/6
https://gist.github.com/allanmac/5043569
https://docs.nvidia.com/cuda/parallel-thread-execution/

2025-01-20 13:03 UTC, manato commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  if (idx < num_points) {
same as https://github.com/autowarefoundation/autoware.universe/pull/9454#discussion_r1922372362

2025-01-20 13:44 UTC, manato commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  InputPointType * d_points, uint32_t * output_mask, int num_points, float min_x, float min_y,
> I had heard that the compiler will only consider the keyword if all the pointers have it. Is that true?

You seem to be right. From my experience, adding `__restrict__` took effect even though I added it partially. But the [official document](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html?highlight=__restrict__#restrict) says "all pointer arguments need to be made restricted for the compiler optimizer to derive any benefit", so the official document should be adhered to. Thanks for pointing out. It was a good learning opportunity.

2025-01-20 14:59 UTC, manato commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +      point.time_stamp > twist.last_stamp_nsec ? point.time_stamp - twist.last_stamp_nsec : 0;
To my best knowledge, a ternary operator possibly causes different control flows for threads within the same warp. To me, "masking" looks like it is what warp divergence, in which the executions of threads with different conditions are serialized. However, according to the [document](https://docs.nvidia.com/cuda/parallel-thread-execution/#independent-thread-scheduling) you shared, recent GPU (which has volta arch or later) obtains independent thread scheduling, which seems to allow diverge and reconverge at sub-warp granularity. In that case, you may not need to care about this kinds of small optimization to avoid divergence.

2025-01-20 15:00 UTC, manato commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +    azimuth_diff = azimuth_diff < 0.f ? azimuth_diff + 2 * M_PI : azimuth_diff;
same as https://github.com/autowarefoundation/autoware.universe/pull/9454#discussion_r1922532090

2025-01-21 00:14 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  if (idx < num_points) {
Resolving this as per the previous comment

2025-01-21 00:14 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  if (idx < num_points) {
Resolving this as per the previous comment

2025-01-21 00:14 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +    azimuth_diff = azimuth_diff < 0.f ? azimuth_diff + 2 * M_PI : azimuth_diff;
Resolving this as per the previous comment

2025-01-21 00:15 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  InputPointType * d_points, uint32_t * output_mask, int num_points, float min_x, float min_y,
Will accept the suggestion and add the keyword to all variables

2025-01-23 07:22 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/config/cuda_pointcloud_preprocessor.param.yaml
> +    mirror_crop.max_z: -1.0
Addressed in [5e0cc47](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5e0cc4758ea69a7c2fd710b3b318710d2f80b93e)

2025-01-28 10:56 UTC, manato approved these changes
@knzo25 
Thank you for responding to my comments. I viewed the code and confirmed my major concern has been gone. Once the comments from @mojomex are solved, I believe this PR can be merged.

2025-02-05 07:13 UTC, knzo25 commented
@mojomex 
Max, I am sorry, but in [59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e) I changed a lot of things by deleting the cuda adapter node and moving its implementation to cuda (now the only hotspot is the host -> device copy, as you can see in the updated table)

2025-02-05 07:29 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +  const autoware::point_types::PointXYZIRCAEDT * input_buffer =
Sorry, but I ended up removing the adapter since it was heavier than the preprocessing :sweat_smile: 
[59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e)

2025-02-05 07:29 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +  }
Sorry, but I ended up removing the adapter since it was heavier than the preprocessing 😅
[59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e)

2025-02-05 07:29 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +  for (std::size_t i = 0; i < input_pointcloud_msg_ptr->width * input_pointcloud_msg_ptr->height;
Sorry, but I ended up removing the adapter since it was heavier than the preprocessing 😅
[59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e)

2025-02-05 07:29 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +  for (std::size_t i = 0; i < input_pointcloud_msg_ptr->width * input_pointcloud_msg_ptr->height;
Sorry, but I ended up removing the adapter since it was heavier than the preprocessing 😅
[59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e)

2025-02-05 07:31 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +  // Set max rings to the next power of two
In the new version
[59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e)

Autodetection is performed automatically with very little overhead :+1:

2025-02-05 07:33 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +  const autoware::point_types::PointXYZIRCAEDT * input_buffer =
Sorry, but I ended up removing the adapter since it was heavier than the preprocessing 😅
[59144d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/59144d8ce1f9e4a6a33e5dfb493ab26fcefdc111) and [5482f9c](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5482f9c4cd7d9764e80eb937ddf73e2ca702d76e)

2025-02-05 07:40 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
Regarding data containers, I am using only thrust vectors. However, they induce unexpected syncs, which I find annoying so may need to change some to our `make_unique` style.

2025-02-05 09:22 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +      : 0;
Addressed in [c554290](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/c55429062aca9be4658adfb6977a454693076d29)

2025-02-05 09:23 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
Regarding the chonkyness, it was addressed in 
[303b9ed](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/303b9ede65c8a748a1dd495df78ee3eda8d1b066)

2025-02-05 09:24 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +}
Unused kernels were deleted in
[303b9ed](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/303b9ede65c8a748a1dd495df78ee3eda8d1b066)

2025-02-05 09:26 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_organized_pointcloud_adapter/cuda_organized_pointcloud_adapter_node.cpp
> +{
I had not done in on purpose for now.
right now the check lives in the pointcloud preprocessor, but as there are more cuda nodes that treat the memory directly, it would be better to have the check somewhere easily accessible like autoware point types, which I planned to do as soon as this got merged.

In the meantime, just reimplemented the logic in this node
[d6ad9db](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/d6ad9db83987f4e7f9cc4283b3787909d237562c)

2025-02-05 09:55 UTC, knzo25 commented
@manato 
It seems to me that the host -> device transfer is too slow. It is paged (ROS), but it still seems off to me. Do you have a way to check these concerns? The theoretical bandwidth that I got with the cuda samples was super different than the bandwidth reported by nsight :cry:  and there was nothing else happening on the GPU at the time

2025-02-05 11:51 UTC, amadeuszsz requested changes
Added few minor comments. Regarding runtime, there was an issue with point cloud rings (see attached image), but I believe it's already fixed in https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/f10022444e70452b8dbced7990a5351d36d05d71
![Screenshot from 2025-02-05 20-21-52](https://github.com/user-attachments/assets/c466a95b-8ce8-4fd8-8983-05a11375e87b)

About package architecture, I wonder if keeping cuda kernels with base c++ functions in same `.cu` files is the best way for doing this. On opposite side, kernels consist of actual cuda code and helper _launch_ functions. I will let it up to you as you better see amount of remaining code here and potentially future development path. It may not be worth doubling the number of files.

For cuda kernels code, I will address my comments in next review, I need more time 🙏🏻

2025-02-05 11:51 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/CMakeLists.txt
> +endif()
nit:
Consider to add
```
elseif(CMAKE_BUILD_TYPE STREQUAL "Debug")
  list(APPEND CMAKE_CUDA_FLAGS "-g" "-G")
  list(APPEND CUDA_NVCC_FLAGS "-g" "-G")
endif()
```
to make cuda kernels debugging possible.

2025-02-05 11:51 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/CMakeLists.txt
> +endif()
nit:
Can we already address iron and jazzy distro?

2025-02-05 11:51 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.hpp
> +  void set3DUndistortion(bool value);
Function declarations and definitions usually consist of same parameter names (`value` vs. `use_3d_undistortion`)

2025-02-05 11:51 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.hpp
> +#include <vector>
Unused header

2025-02-05 11:51 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/outlier_kernels.hpp
> +#include "autoware/cuda_pointcloud_preprocessor/types.hpp"
Unused header

2025-02-05 11:51 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/organize_kernels.hpp
> +#include "autoware/cuda_pointcloud_preprocessor/types.hpp"
Unused header

2025-02-14 00:31 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/CMakeLists.txt
> +endif()
Although there would not be any issue with adding this, I say no other mention to iron/jazzy in universe, and I believe those definitions should be repository-wide to avoid misunderstandings.

2025-02-14 01:14 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/organize_kernels.hpp
> +#include "autoware/cuda_pointcloud_preprocessor/types.hpp"
Addressed in [d2505ee](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/d2505ee9d7ccda6bc014747b7b7d1ecc2bfeec8b)

2025-02-14 01:14 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/outlier_kernels.hpp
> +#include "autoware/cuda_pointcloud_preprocessor/types.hpp"
Addressed in [d2505ee](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/d2505ee9d7ccda6bc014747b7b7d1ecc2bfeec8b)

2025-02-14 01:15 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.hpp
> +#include <vector>
Addressed in [d2505ee](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/d2505ee9d7ccda6bc014747b7b7d1ecc2bfeec8b)

2025-02-14 01:15 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.hpp
> +  void set3DUndistortion(bool value);
Addressed in [186fff9](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/186fff9d1dac57adf966dc264f964e96a118126c)

2025-02-14 01:15 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/CMakeLists.txt
> +endif()
Addressed in [2b9f654](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/2b9f654a15aa20dec801b8ab258b6496a2ca6015)

2025-02-14 01:15 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/undistort_kernels.cu
> +    std::uint64_t twist_global_stamp_nsec = twist_stamp;
Addressed in [fa36260](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/fa36260cf79670d2bc222261597ea19cf59247e6)

2025-02-14 01:16 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/launch/cuda_pointcloud_preprocessor.launch.xml
> +  <node pkg="cuda_pointcloud_preprocessor" exec="cuda_pointcloud_preprocessor_node" name="cuda_pointcloud_preprocessor" output="screen">
Addressed in [48b39cd](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/48b39cd8ec84df413c8ff51344cc254ad32f17a2)

2025-02-14 01:16 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/launch/cuda_pointcloud_preprocessor.launch.xml
> +  <arg name="cuda_pointcloud_preprocessor_param_file" default="$(find-pkg-share cuda_pointcloud_preprocessor)/config/cuda_pointcloud_preprocessor.param.yaml"/>
Addressed in [48b39cd](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/48b39cd8ec84df413c8ff51344cc254ad32f17a2)

2025-02-14 01:17 UTC, knzo25 commented
@amadeuszsz 
After checking some rosbags, the weird behavior of the pointclouds is related to either the VLP16 or its driver. I confirmed that the output of both the intermediate pointclouds and the concat are the same in the old implementation and this

2025-02-25 23:37 UTC, knzo25 commented
@amadeuszsz 
Did you have time to check this?

2025-03-03 03:36 UTC, amadeuszsz requested changes
Minor comments. Please, check also this [one](https://github.com/autowarefoundation/autoware.universe/pull/9454#pullrequestreview-2523189609).
Regardless code review, during testing with rosbag, my rviz instance crashes
```
terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)
```
It happens when timer is restarted (`--loop`) and only if output pointcloud from `autoware_cuda_pointcloud_preprocessor` is visualized. Could you please check if it happens to you too? If so, I would appreciate if you can investigate this issue 🙏🏻

Please also take a look on failing CI [[1](https://github.com/autowarefoundation/autoware.universe/actions/runs/13620760192/job/38069860207?pr=9454)][[2](https://github.com/autowarefoundation/autoware.universe/actions/runs/13620760205/job/38069865806?pr=9454)].

2025-03-03 03:36 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/common_kernels.cu
> +      const CropBoxParameters & crop_box_parameters = crop_box_parameters_ptr[i];
nit: for parameters shared across threads, use of [shared memory](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#shared-memory) might be recommended approach

```suggestion
  // Cache crop box params
  extern __shared__ CropBoxParameters shared_crop_box_params[];
  for (int i = threadIdx.x; i < num_crop_boxes; i += blockDim.x) {
    if (i < num_crop_boxes) {
      shared_crop_box_params[i] = crop_box_parameters_ptr[i];
    }
  }
  __syncthreads();

  for (int idx = blockIdx.x * blockDim.x + threadIdx.x; idx < num_points;
       idx += blockDim.x * gridDim.x) {
    const float x = d_points[idx].x;
    const float y = d_points[idx].y;
    const float z = d_points[idx].z;

    std::uint32_t mask = 1;

    for (int i = 0; i < num_crop_boxes; i++) {
      const CropBoxParameters & crop_box_parameters = shared_crop_box_params[i];
```

2025-03-03 03:36 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  const InputPointType * input_points, InputPointType * output_points, int num_points,
@knzo25 could you please double check all input arrays across kernels? I think for some of them `__restrict__` keyword might be also applicable. I don't know if you missed it or skipped on purpose. 
I unresolved this conversation, please resolve it again after reading this comment 🙏🏻

2025-03-03 04:01 UTC, mojomex submitted a review, later dismissed
I have some smaller schema/lifetime/readability comments but otherwise looking good!

2025-03-06 06:56 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/common_kernels.cu
> +      const CropBoxParameters & crop_box_parameters = crop_box_parameters_ptr[i];
@amadeuszsz 
I did try that, and the performance was slightly worse :c

2025-03-06 07:04 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/common_kernels.cu
> +      const CropBoxParameters & crop_box_parameters = crop_box_parameters_ptr[i];
I measured with cuda event and for me it was same 😄 I bet this kernel is too light to see any difference. Anyway, please feel free to resolve this conversation.

2025-03-06 08:19 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/config/cuda_pointcloud_preprocessor.param.yaml
> +    crop_box.max_z: [-1.0]
Those were on purpose, but better to left them empty
[bc4d470](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/bc4d4702761618210ff2c8b6d80c5b23fd7283dc)

2025-03-06 08:20 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/schema/cuda_pointcloud_preprocessor.schema.json
> +          "description": "An array in which each elemt is the minimum x value in a crop box",
Sorry, addressed in [5dba7b3](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/5dba7b307c9140fc44498604733464ebf2e3d9ee)

2025-03-06 08:20 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.hpp
> +  ~CudaPointcloudPreprocessorNode() = default;
Addressed in [92b04a3](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/92b04a37f50d04aaa80161f3946836ec1ea55ace)

2025-03-06 08:21 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp
> +    }
Thanks. addressed in [2449e67](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/2449e67b6685056d7c972a244dd8b0cc5a85b075)

2025-03-06 08:21 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp
> +      angular_velocity_queue_.pop_front();
Thanks. Addressed in [2449e67](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/2449e67b6685056d7c972a244dd8b0cc5a85b075)

2025-03-06 08:21 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp
> +      angular_velocity_queue_.pop_front();
Thanks. Addressed in [2449e67](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/2449e67b6685056d7c972a244dd8b0cc5a85b075)

2025-03-06 08:21 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/include/autoware/cuda_pointcloud_preprocessor/undistort_kernels.hpp
> +  const std::deque<geometry_msgs::msg::TwistWithCovarianceStamped> & twist_queue,
Addressed in [17af8d8](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/17af8d871a1e8270713209c9bd92874726611102)

2025-03-06 08:22 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/schema/cuda_pointcloud_preprocessor.schema.json
> +      ],
Addressed in [652d168](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/652d16830a5f0ac366fb685784c434959f6fde7a)

2025-03-06 08:25 UTC, knzo25 commented
@amadeuszsz 

>@knzo25 could you please double check all input arrays across kernels? I think for some of them __restrict__ keyword might be also applicable. I don't know if you missed it or skipped on purpose.
I unresolved this conversation, please resolve it again after reading this comment 🙏🏻

Could not answer this one, but the extract kernel could indeed use restrict. The kernel alone, strictly speaking can not, but due to how the indexes are computed there is no problem

2025-03-06 08:26 UTC, knzo25 commented
@amadeuszsz 
Regarding CI/CD, I have not executed in ob purpose since the blackboard is not yet added to autoware.
I will investigate the loop error tomorrow

2025-03-10 07:32 UTC, knzo25 commented
> terminate called after throwing an instance of 'std::system_error'
  what():  Invalid argument
Aborted (core dumped)
It happens when timer is restarted (--loop) and only if output pointcloud from autoware_cuda_pointcloud_preprocessor is visualized. Could you please check if it happens to you too? If so, I would appreciate if you can investigate this issue 🙏🏻

Sorry, I only experienced it once in several experiments, and the pointcloud itself at the time was valid (checked with ros2 topic echo)

2025-03-12 06:16 UTC, amadeuszsz requested changes

2025-03-12 06:16 UTC, amadeuszsz commented on sensing/autoware_cuda_pointcloud_preprocessor/config/cuda_pointcloud_preprocessor.param.yaml
> +    crop_box.max_z: []
We can't use empty array as parameter's values yet (https://github.com/ros2/rclcpp/issues/1955)

2025-03-12 12:03 UTC, mojomex commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor_node.cpp
> +  geometry_msgs::msg::TransformStamped::SharedPtr tf_base2imu_ptr =
Resolved in 2449e67

2025-03-17 05:47 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  const InputPointType * input_points, InputPointType * output_points, int num_points,
@amadeuszsz 
Ahh now I can reply here. Don't know why but before I could not

Answer: the extract kernel could indeed use restrict. The kernel alone, strictly speaking can not, but due to how the indexes are computed there is no problem

2025-03-17 05:48 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/src/cuda_pointcloud_preprocessor/cuda_pointcloud_preprocessor.cu
> +  const InputPointType * input_points, InputPointType * output_points, int num_points,
Addressed in [68d1e42](https://github.com/autowarefoundation/autoware.universe/pull/9454/commits/68d1e421ec79074c289c3b30e6e68c14342dfddb)

2025-03-17 06:08 UTC, knzo25 commented on sensing/autoware_cuda_pointcloud_preprocessor/config/cuda_pointcloud_preprocessor.param.yaml
> +    crop_box.max_z: []
Addressed in 
9ededc5

2025-03-17 06:11 UTC, amadeuszsz approved these changes
LGTM!

2025-03-18 10:34 UTC, merged