feat(autoware_vehicle_info_utils): move autoware_vehicle_info_utils to autoware.core
autowarefoundation/autoware.universe pull request #9694
Opened 2024-12-19 09:03 UTC by cyn-liu

## Description
We are porting autoware_vehicle_info_utils to autoware.core, and this PR removes the package from autoware.universe.

## Related links

**Parent Issue:**

- Issue: https://github.com/autowarefoundation/autoware.core/issues/131
- This has to be merged with the following pull requests: https://github.com/autowarefoundation/autoware.core/pull/135

## How was this PR tested?

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

2025-01-20 04:07 UTC, soblin approved these changes

2025-01-29 07:05 UTC, youtalk requested changes
We need to resolve the merge conflicts and apply the fixes to https://github.com/autowarefoundation/autoware.core/pull/170 as well.

2025-02-03 04:50 UTC, youtalk approved these changes
Resolved by myself.

2025-02-03 04:52 UTC, youtalk commented
@mitsudome-r I hope it's time to merge this and https://github.com/autowarefoundation/autoware.core/pull/170.

2025-02-05 03:51 UTC, mitsudome-r commented
This PR must be merged in the following order to avoid build failure with autoware-nightly.repos:
* Merge https://github.com/autowarefoundation/autoware.universe/pull/10070
* https://github.com/autowarefoundation/autoware/pull/5731

2025-02-22 05:36 UTC, merged